# Generated by Django 5.1.1 on 2026-03-14 06:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantFeeProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('merchant_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('phone_number', models.CharField(db_index=True, default='0000000000', max_length=15, unique=True)),
                ('merchant_name', models.CharField(max_length=255)),
                ('mdr_rate', models.DecimalField(decimal_places=4, help_text='Merchant Discount Rate as a decimal (e.g., 0.0180 = 1.80%)', max_digits=6)),
                ('gst_rate', models.DecimalField(decimal_places=4, help_text='GST rate on MDR as a decimal (e.g., 0.18 = 18%)', max_digits=6)),
                ('amc_fees', models.DecimalField(decimal_places=2, default=0, help_text='Annual Maintenance Charge in INR', max_digits=10)),
                ('settlement_cycle', models.CharField(choices=[('T+1', 'T+1'), ('T+2', 'T+2'), ('T+3', 'T+3')], default='T+1', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Merchant Fee Profile',
                'verbose_name_plural': 'Merchant Fee Profiles',
                'db_table': 'merchant_fee_profiles',
            },
        ),
        migrations.CreateModel(
            name='FeePlanChangeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mdr_rate', models.DecimalField(decimal_places=4, max_digits=6)),
                ('gst_rate', models.DecimalField(decimal_places=4, max_digits=6)),
                ('amc_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('settlement_cycle', models.CharField(choices=[('T+1', 'T+1'), ('T+2', 'T+2'), ('T+3', 'T+3')], default='T+1', max_length=10)),
                ('effective_date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_plan_logs', to='transactions.merchantfeeprofile', to_field='merchant_id')),
            ],
            options={
                'verbose_name_plural': 'Fee Plan Change Logs',
                'db_table': 'fee_plan_change_logs',
                'ordering': ['-effective_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('settlement_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('mdr_deducted', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gst_deducted', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_deducted', models.DecimalField(decimal_places=2, help_text='Total tax = MDR + GST', max_digits=14)),
                ('net_payout', models.DecimalField(decimal_places=2, max_digits=14)),
                ('transaction_count', models.PositiveIntegerField(default=0)),
                ('settlement_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('disputed', 'Disputed'), ('settled', 'Settled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='transactions.merchantfeeprofile', to_field='merchant_id')),
            ],
            options={
                'db_table': 'settlements',
                'ordering': ['-settlement_date'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('expected_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('discrepancy', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('raised_by', models.CharField(default='reconciliation_agent', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_issues', to='transactions.merchantfeeprofile', to_field='merchant_id')),
                ('settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_issues', to='transactions.settlement', to_field='settlement_id')),
            ],
            options={
                'db_table': 'reconciliation_issues',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('mode', models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('upi', 'UPI'), ('net_banking', 'Net Banking'), ('wallet', 'Wallet')], default='credit_card', max_length=20)),
                ('card_last_four', models.CharField(blank=True, default='', max_length=4)),
                ('customer_name', models.CharField(blank=True, default='', max_length=255)),
                ('transaction_date', models.DateTimeField()),
                ('is_refund', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='transactions.merchantfeeprofile', to_field='merchant_id')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='transactions.settlement', to_field='settlement_id')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-transaction_date'],
            },
        ),
    ]
